name = "frontend"
pages_build_output_dir = "./site"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]
services = [
    {binding = "BACKEND", service = "backend"}
]

[[env.preview.services]]
service = "backend"
binding = "BACKEND"

[[env.production.services]]
service = "backend"
binding = "BACKEND"

