#:schema node_modules/wrangler/config-schema.json
name = "photo-service"
main = "build/worker/shim.mjs"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]
services = [
    {binding = "AUTH", service = "authentication-service"}
]

[build]
command = "cargo install -q worker-build && worker-build --release"

[[ d1_databases ]]
binding = "DB"
database_name = "photo-service"
database_id = "f76fd8c5-7c1a-4bd2-be51-6b697a87ee62"

