#:schema node_modules/wrangler/config-schema.json
name = "backend"
main = "build/worker/shim.mjs"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]
# This creates a private worker without a public URl
workers_dev = false

[build]
command = "cargo install -q worker-build && worker-build --release"

[[kv_namespaces]]
binding = "COUNTRY_CACHE"
id = "895af0cf03054686b1a079172ab67261"
preview_id = "a4eef864a0a648c9adb030a8a4c1f47a"

[[env.preview.kv_namespaces]]
binding = "COUNTRY_CACHE"
id = "a4eef864a0a648c9adb030a8a4c1f47a"

[[env.production.kv_namespaces]]
binding = "COUNTRY_CACHE"
id = "895af0cf03054686b1a079172ab67261"