name = "rusty-chatroom-frontend"
pages_build_output_dir = "./site"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]
services = [
    {binding = "BACKEND", service = "rusty-chatroom"},
    {binding = "AUTH", service = "authentication"},
]

[[env.preview.services]]
service = "rusty-chatroom"
binding = "BACKEND"

[[env.production.services]]
service = "rusty-chatroom"
binding = "BACKEND"

[[env.preview.services]]
service = "authentication"
binding = "AUTH"

[[env.production.services]]
service = "authentication"
binding = "AUTH"

